app/tweet/models.py
from datetime import datetime

from .. import db


class Tweet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    text = db.Column(db.String(150), nullable=False)
    created = db.Column(db.DateTime, default=datetime.now)

app/tweet/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import InputRequired


class TweetForm(FlaskForm):
    text = TextAreaField('Message',
                         validators=[InputRequired('Message is required')])

app/tweet/__init__.py
from flask import Blueprint

from app import login_manager
from app.user.models import User

tweet_page = Blueprint('tweet_page', __name__)

from app.tweet import views


@login_manager.user_loader
def get_user(user_id):
    return User.query.get(int(user_id))

app/tweet/views.py
from datetime import datetime

from flask import flash, abort
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user

from app.user.models import User
from app.user.models import followers
from . import tweet_page
from .forms import TweetForm
from .models import Tweet
from .. import db, app


@app.template_filter('time_since')
def time_since(delta):
    seconds = delta.total_seconds()

    days, seconds = divmod(seconds, 86400)
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)

    if days > 0:
        return '%dd' % days
    elif hours > 0:
        return '%dh' % hours
    elif minutes > 0:
        return '%dm' % minutes
    else:
        return 'Just now'


@tweet_page.route('/')
def tweets():
    tweets_all = Tweet.query.all()
    current_time = datetime.now()
    return render_template('tweet/tweets.html',
                           tweets=tweets_all,
                           current_time=current_time)


@tweet_page.route('/timeline', defaults={'username': None})
@tweet_page.route('/timeline/<username>')
@login_required
def timeline(username):
    form = TweetForm()

    if username:
        user = User.query.filter_by(username=username).first()
        if not user:
            abort(404)
        tweets = Tweet.query.filter_by(user=user) \
            .order_by(Tweet.created.desc()).all()
    else:
        user = current_user
        tweets = Tweet.query.join(followers, (followers.c.followee_id == Tweet.user_id)) \
            .filter(followers.c.follower_id == current_user.id) \
            .order_by(Tweet.created.desc()).all()

    current_time = datetime.now()

    who_watch = User.query \
        .filter(User.id != user.id) \
        .order_by(db.func.random()) \
        .limit(4).all()

    followed_by = user.followed_by.all()

    return render_template('tweet/timeline.html',
                           form=form,
                           tweets=tweets,
                           current_time=current_time,
                           current_user=user,
                           who_watch=who_watch,
                           followed_by=followed_by)


@tweet_page.route('/post_tweet', methods=['POST'])
@login_required
def post_tweet():
    form = TweetForm()
    if form.validate():
        tweet = Tweet(
            user_id=current_user.id,
            text=form.text.data
        )
        db.session.add(tweet)
        db.session.commit()
        return redirect(url_for('tweet_page.timeline'))
    return flash('Something went wrong.')

app/templates/tweet/timeline.html
{% extends 'base.html' %}
{% from '_formhelper.html' import render_field %}

{% block title %}
    User Profile
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="text-center bold">Timeline</h3>
            </div>

            <div class="col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row pad">
                            <div class="col-lg-12">
                                <img src="{{ current_user.image }}" class="img-responsive img-circle center-block"
                                     alt="Image"/>
                            </div>
                        </div>
                        <div class="row pad">
                            <div class="col-lg-4 col-lg-offset-2 text-center">
                                <strong>
                                    Tweets <br/>
                                    {{ tweets|length }}
                                </strong>
                            </div>
                            <div class="col-lg-4 text-center">
                                <strong>
                                    Followers <br/>
                                    {{ followed_by|length }}
                                </strong>
                            </div>
                        </div>
                    </div>
                    <ul class="list-group">
                        <a class="list-group-item" data-toggle="modal" href="#newPost" data-backdrop="static"
                           data-keboard="false">
                            <i class="glyphicon glyphicon-plus-sign"></i> Post New Message
                        </a>
                    </ul>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% for tweet in tweets %}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="thumbnail">
                                    <div class="caption">
                                        <div class="row">
                                            <div class="col-lg-10">
                                                <!-- <i class="glyphicon glyphicon-user"></i>  -->
                                                <img src="{{ tweet.user.image }}" style="width: 30px; height: 30px;"
                                                     class="img-circle">
                                                <strong>
                                                    <a href="{{ url_for('user_page.profile', username=tweet.user.username) }}">
                                                        {{ tweet.user.name }}
                                                    </a>
                                                </strong>
                                                <small><em>@{{ tweet.user.username }}</em></small>
                                            </div>
                                            <div class="col-lg-2 text-right">
                                                {{ (current_time - tweet.created)|time_since }}
                                            </div>
                                        </div>
                                        <div class="row pad">
                                            <div class="col-lg-12">
                                                {{ tweet.text }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Who To Watch</h3>
                    </div>
                    <ul class="list-group">
                        {% for user in who_watch %}
                            <li class="list-group-item">
                                {{ user.name }}
                                <div>
                                    <strong>
                                        <a href="{{ url_for('user_page.profile', username=user.username) }}">
                                            @{{ user.username }}
                                        </a>
                                    </strong>
                                    <span class="pull-right">
										{{ user.followed_by.all()|length }} Followers
									</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="modal fade" id="newPost">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Post New Message</h4>
                    </div>
                    <form method="POST" action="{{ url_for('tweet_page.post_tweet') }}">
                        {{ form.csrf_token }}
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-lg-8 col-lg-offset-2">
                                    <div class="form-group">
                                        <label>Enter new <a href="./">Twitter!</a> post</label>
                                        {{ render_field(form.text, class="form-control", rows=6,
                                        required='reqired', placeholder="Type tweet text here...") }}
                                    </div>
                                    <div class="form-group">
                                        By posting on our platform, you agree to our <a href="#">Terms and
                                        Conditions</a>.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                <i class="glyphicon glyphicon-ban-circle"></i> Close
                            </button>
                            <button type="submit" class="btn btn-primary">
                                <i class="glyphicon glyphicon-send"></i> Post
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/tweet/tweets.html
{% extends 'base.html' %}

{% block title %}
    Tweets
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="text-center bold">Tweets</h3>
            </div>

            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% for tweet in tweets %}
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="thumbnail">
                                        <div class="caption">
                                            <div class="row">
                                                <div class="col-lg-10">
                                                    <!-- <i class="glyphicon glyphicon-user"></i>  -->
                                                    <img src="{{ tweet.user.image }}" style="width: 30px; height: 30px;"
                                                         class="img-circle">
                                                    <strong>
                                                        <a href="{{ url_for('user_page.profile', username=tweet.user.username) }}">
                                                            {{ tweet.user.name }}
                                                        </a>
                                                    </strong>
                                                    <small><em>@{{ tweet.user.username }}</em></small>
                                                </div>
                                                <div class="col-lg-2 text-right">
                                                    {{ (current_time - tweet.created)|time_since }}
                                                </div>
                                            </div>
                                            <div class="row pad">
                                                <div class="col-lg-12">
                                                    {{ tweet.text }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}