app/user/models.py
from datetime import datetime
from functools import partial

from flask_login import UserMixin
from slugify import slugify
from sqlalchemy import Column

from .. import db

NotNullColumn = partial(Column, nullable=False)

followers = db.Table('follower',
                     db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('followee_id', db.Integer, db.ForeignKey('user.id')))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250))
    username = NotNullColumn(db.String(250), unique=True)
    email = NotNullColumn(db.String, unique=True)
    password = NotNullColumn(db.String)
    image = db.Column(db.String(100))
    created = db.Column(db.DateTime, default=datetime.now)
    slug = db.Column(db.String(), nullable=True)
    tweets = db.relationship('Tweet', backref='user', lazy='dynamic')
    following = db.relationship('User', secondary=followers,
                                primaryjoin=(followers.c.follower_id == id),
                                secondaryjoin=(followers.c.followee_id == id),
                                backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')
    followed_by = db.relationship('User', secondary=followers,
                                  primaryjoin=(followers.c.followee_id == id),
                                  secondaryjoin=(followers.c.follower_id == id),
                                  backref=db.backref('followees', lazy='dynamic'), lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.name)

    def __init__(self, *args, **kwargs):
        if 'slug' not in kwargs:
            kwargs['slug'] = slugify(kwargs.get('name', ''))
        super().__init__(*args, **kwargs)

app/user/forms.py
from flask_uploads import IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, Length, EqualTo, DataRequired, Email


class RegisterForm(FlaskForm):
    name = StringField('Full name', validators=[Length(max=100,
                                                       message='Your name can\'t be more than 100 characters.')])
    username = StringField('Full name', validators=[InputRequired('A username is required.'),
                                                    Length(max=100,
                                                           message='Your name can\'t be more than 100 characters.')])
    email = EmailField('Email', validators=[InputRequired('Email is required.'),
                                            Length(max=30, message='Your username is too many characters.')])

    password = PasswordField('Password',
                             validators=[InputRequired('A password is required.'),
                                         EqualTo('confirm_password', message='Password must match')])
    confirm_password = PasswordField('Confirm password',
                                     validators=[DataRequired()])

    image = FileField(validators=[FileAllowed(IMAGES, 'Only images are accepted.')])


class LoginForm(FlaskForm):
    email = EmailField('Email',
                       validators=[InputRequired('A password is required.'),
                                   Email()])
    password = PasswordField('Password',
                             validators=[InputRequired('A password is required.')])
    remember = BooleanField('Remember me')

app/user/__init__.py
from flask import Blueprint

from app import login_manager
from app.user.models import User

user_page = Blueprint('user_page', __name__)

from app.user import routes


@login_manager.user_loader
def get_user(user_id):
    return User.query.get(int(user_id))

app/user/routes.py
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from flask_uploads import UploadSet, configure_uploads, IMAGES
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash

from . import user_page
from .forms import RegisterForm, LoginForm
from .models import User
from .. import app, db, config

photos = UploadSet('photos', IMAGES)
configure_uploads(app, photos)


@user_page.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            image_filename = f'../../static/images/{photos.save(form.image.data)}'
        except TypeError:
            image_filename = config.Config.DEFAULT_URL_IMG

        user = User(name=form.name.data,
                    email=form.email.data,
                    image=image_filename,
                    password=generate_password_hash(form.password.data))
        db.session.add(user)
        try:
            db.session.commit()
            flash('You have been successfully registered.')
            return redirect(url_for('index'))
        except IntegrityError:
            db.session.rollback()
            flash('This email is already exist.')
    return render_template('user/register.html',
                           form=form)


@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            if not user:
                flash('Login failed.')

            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash('You have been successfully logged in.')
                return redirect(url_for('index'))
            flash('Login failed.')
        except AttributeError:
            pass

    return redirect(url_for('index'))


@user_page.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('index'))


@user_page.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html',
                           current_user=current_user)


@user_page.route('/timeline')
@login_required
def timeline():
    return render_template('timeline.html')

app/user/views.py
from datetime import datetime

from flask import render_template, redirect, url_for, flash, abort
from flask_login import login_user, login_required, logout_user, current_user
from flask_uploads import UploadSet, configure_uploads, IMAGES
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash

from app.tweet.models import Tweet
from . import user_page
from .forms import RegisterForm, LoginForm
from .models import User
from .. import app, db, config

photos = UploadSet('photos', IMAGES)
configure_uploads(app, photos)


@user_page.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            image_filename = f'../../static/images/{photos.save(form.image.data)}'
        except TypeError:
            image_filename = config.Config.DEFAULT_URL_IMG

        user = User(name=form.name.data,
                    username=form.username.data,
                    email=form.email.data,
                    image=image_filename,
                    password=generate_password_hash(form.password.data))
        db.session.add(user)
        try:
            db.session.commit()
            flash('You have been successfully registered.')
            login_user(user)
            return redirect(url_for('user_page.profile'))
        except IntegrityError:
            db.session.rollback()
            flash('This email is already exist.')
    return render_template('user/register.html',
                           form=form)


@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            if not user:
                flash('Login failed.')

            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash('You have been successfully logged in.')
                return redirect(url_for('user_page.profile'))
            flash('Login failed.')
        except AttributeError:
            pass

    return redirect(url_for('index'))


@user_page.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('index'))


@user_page.route('/profile', defaults={'username': None})
@user_page.route('/profile/<username>')
@login_required
def profile(username):
    display_follow = True
    if username:
        user = User.query.filter_by(username=username).first()
        if not user:
            abort(404)
    else:
        user = current_user
    tweets = Tweet.query.filter_by(user=user).all()
    current_time = datetime.now()
    followed_by = user.followed_by.all()
    following = user.following.all()

    if current_user == user:
        display_follow = False
    elif current_user in followed_by:
        display_follow = False

    who_watch = User.query \
        .filter(User.id != user.id) \
        .order_by(db.func.random()) \
        .limit(4).all()

    return render_template('user/profile.html',
                           current_user=user,
                           tweets=tweets,
                           current_time=current_time,
                           followed_by=followed_by,
                           following=following,
                           display_follow=display_follow,
                           who_watch=who_watch)

app/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}
    User Profile
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="text-center bold">User's Profile</h3>
            </div>
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row pad">
                            <div class="col-lg-12">
                                <img src="{{ current_user.image }}" class="img-responsive img-circle center-block"
                                     alt="Image"
                                     style="height: 220px;"/>
                            </div>
                        </div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <i class="glyphicon glyphicon-user"></i> NAME:
                            <strong class="pull-right">{{ current_user.name }}</strong>
                        </li>
                        <li class="list-group-item">
                            <i class="glyphicon glyphicon-user"></i> Username:
                            <strong class="pull-right">{{ current_user.username }}</strong>
                        </li>
                        <li class="list-group-item">
                            <i class="glyphicon glyphicon-th"></i> Email:
                            <strong class="pull-right"><em>{{ current_user.email }}</em></strong>
                        </li>
                        <li class="list-group-item">
                            <i class="glyphicon glyphicon-calendar"></i> MEMBER SINCE:
                            <strong class="pull-right">{{ current_user.created.strftime('%B %d, %Y') }}</strong>
                        </li>
                        <li class="list-group-item">
                            <i class="glyphicon glyphicon-th-list"></i> FOLLOWERS COUNT:
                            <strong class="pull-right">{{ followed_by|length }}</strong>
                        </li>
                        {% if display_follow %}
                            <li class="list-group-item">
                                &nbsp;<strong class="pull-right">
                                <a href="{{ url_for('follower_page.follow', username=current_user.username) }}">
                                    FOLLOW
                                </a>
                            </strong>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>

            <div class="col-lg-5">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4><strong>Activity</strong></h4>
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tweets" aria-controls="tweets" role="tab" data-toggle="tab">Tweets</a>
                                </li>
                                <li role="presentation">
                                    <a href="#followers" aria-controls="followers" role="tab"
                                       data-toggle="tab">Followers</a>
                                </li>
                                <li role="presentation">
                                    <a href="#followings" aria-controls="followings" role="tab"
                                       data-toggle="tab">Followings</a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="tweets">
                                    {% for tweet in tweets %}
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="row pad">
                                                    <div class="col-lg-2">
                                                        <img src="{{ tweet.user.image }}" class="img-circle"
                                                             style="width: 60px; height: 60px;"/>
                                                    </div>
                                                    <div class="col-lg-10">
                                                        <div>
                                                            <strong class="mid">
                                                                <a href="{{ url_for('tweet_page.timeline', username=tweet.user.username) }}">
                                                                    {{ tweet.user.name }}
                                                                </a>
                                                            </strong>
                                                            <small><em>@{{ tweet.user.username }}</em></small> .
                                                            {{ (current_time - tweet.created)|time_since }}
                                                        </div>
                                                        <div class="pad">
                                                            {{ tweet.text }}
                                                        </div>
                                                        <a href="{{ url_for('tweet_page.timeline', username=tweet.user.username) }}"
                                                           class="pull-right">
                                                            More
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div role="tabpanel" class="tab-pane" id="followers">
                                    {% for follower in followed_by %}
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="row pad">
                                                    <div class="col-lg-2">
                                                        <img src="{{ follower.image }}" class="img-circle"
                                                             style="width: 60px; height: 60px;"/>
                                                    </div>
                                                    <div class="col-lg-10">
                                                        <div>
                                                            <strong class="mid">{{ follower.name }}</strong>
                                                            <small><em>
                                                                <a href="{{ url_for('user_page.profile', username=follower.username) }}">
                                                                    @{{ follower.username }}
                                                                </a>
                                                            </em></small>
                                                        </div>
                                                        <div class="row pad">
                                                            <hr/>
                                                            <div class="col-lg-12">
                                                                <i class="glyphicon glyphicon-th-list"></i>
                                                                {{ follower.followed_by.all()|length }}
                                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div role="tabpanel" class="tab-pane" id="followings">
                                    {% for follower in following %}
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="row pad">
                                                    <div class="col-lg-2">
                                                        <img src="{{ follower.image }}" class="img-circle"
                                                             style="width: 60px; height: 60px;"/>
                                                    </div>
                                                    <div class="col-lg-10">
                                                        <div>
                                                            <strong class="mid">{{ follower.name }}</strong>
                                                            <small><em>
                                                                <a href="{{ url_for('user_page.profile', username=follower.username) }}">
                                                                    @{{ follower.username }}
                                                                </a>
                                                            </em></small>
                                                        </div>
                                                        <div class="row pad">
                                                            <hr/>
                                                            <div class="col-lg-12">
                                                                <i class="glyphicon glyphicon-th-list"></i>
                                                                {{ follower.followed_by.all()|length }}
                                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Who To Watch</h3>
                    </div>
                    <ul class="list-group">
                        {% for user in who_watch %}
                            <li class="list-group-item">
                                {{ user.name }}
                                <div>
                                    <strong>
                                        <a href="{{ url_for('user_page.profile', username=user.username) }}">
                                            @{{ user.username }}
                                        </a>
                                    </strong>
                                    <span class="pull-right">
										{{ user.followed_by.all()|length }} Followers
									</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user/register.html
{% extends 'base.html' %}
{% from '_formhelper.html' import render_field %}

{% block title %}
    User Profile
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row pad">
            <div class="col-lg-4 col-lg-offset-4 pad">
                <h2 class="text-center bold">Join Twitter! today.</h2>
                <br/>
                <form action="{{ url_for('user_page.register') }}" method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}

                    <div class="form-group">
                        {{ render_field(form.name, class="form-control", placeholder="Enter your full name") }}
                    </div>

                    <div class="form-group">
                        {{ render_field(form.username, class="form-control", placeholder="Enter your username") }}
                    </div>

                    <div class="form-group">
                        {{ render_field(form.email, class="form-control", placeholder="Enter an email") }}
                    </div>

                    <div class="form-group">
                        {{ render_field(form.password, class="form-control", placeholder="Enter your password") }}
                    </div>

                    <div class="form-group">
                        {{ render_field(form.confirm_password, class="form-control", placeholder="Re-enter your password") }}
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlFile1">Profile image</label>
                        {{ render_field(form.image, class="form-control-file ") }}
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-danger btn-block">Sign up</button>
                    </div>
                </form>

                <div class="form-group">
                    <a href="{{ url_for('index') }}"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}